[package]
name = "orbitwave"
version = "0.1.0"
edition = "2021"
authors = [ "Juan-luke Klopper" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
